name: event-sourcing-exploration-local

x-api-environment: &api-environment
  ASPNETCORE_ENVIRONMENT: Development
  ConnectionStrings__Database: Host=db;Port=5432;Database=event-sourcing-exploration;Username=admin;Password=pwd
  Caching__Redis__Enabled: true
  Caching__Redis__ConnectionString: redis:6379
  Caching__Redis__Password: redis-dev-password
  Caching__Redis__UseSsl: false
  Caching__Redis__DefaultDatabase: 0
  Caching__Redis__InstanceName: "event-sourcing-exploration:"
  Caching__Redis__AbortOnConnectFail: false
  Authentication__Jwt__ExpiresInMinutes: 100
  Authentication__Jwt__RefreshTokenExpiresInDays: 7
  Serilog__WriteTo__0__Name: Seq
  Serilog__WriteTo__0__Args__serverUrl: http://seq:80

x-db-environment: &db-environment
  POSTGRES_DB: event-sourcing-exploration
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: pwd

x-frontend-environment: &frontend-environment
  API_URL: http://api:8080

x-common-settings: &common-settings
  restart: unless-stopped
  networks:
    - application_network

services:
  api:
    build:
      context: ./src/backend
      dockerfile: EventSourcingExploration.WebApi/Dockerfile
    container_name: event-sourcing-exploration-local-api
    environment: *api-environment
    <<: *common-settings
    ports:
      - "13002:8080"
    depends_on:
      - db
      - redis
      - seq

  seq:
    image: datalust/seq:latest
    container_name: event-sourcing-exploration-local-seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    ports:
      - "13008:80"
    <<: *common-settings
    volumes:
      - seq_data:/data

  redis:
    image: redis:7-alpine
    container_name: event-sourcing-exploration-local-redis
    <<: *common-settings
    ports:
      - "13006:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass redis-dev-password

  db:
    image: postgres:15-alpine
    container_name: event-sourcing-exploration-local-db
    environment: *db-environment
    <<: *common-settings
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "13004:5432"

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile.local
    container_name: event-sourcing-exploration-local-frontend
    environment: *frontend-environment
    volumes:
      - ./src/frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "13000:5173"
    depends_on:
      - api
    <<: *common-settings

volumes:
  db_data:
    name: event-sourcing-exploration-local-db-data
  redis_data:
    name: event-sourcing-exploration-local-redis-data
  seq_data:
    name: event-sourcing-exploration-local-seq-data
  frontend_node_modules:
    name: event-sourcing-exploration-local-frontend-node-modules

networks:
  application_network:
    name: event-sourcing-exploration-local-network
    driver: bridge
